# vim: set ft=automake :
NULL =
include $(top_srcdir)/Makefile.desktop-files

appletdir = $(datadir)/avant-window-navigator/applets/$(APPLET_NAME)

install-exec-local:
	test -d "$(DESTDIR)$(appletdir)" || mkdir -p "$(DESTDIR)$(appletdir)"
	$(INSTALL) -m 755 "$(APPLET_MAIN_FILE)" "$(DESTDIR)$(appletdir)/$(APPLET_MAIN_FILE)"

uninstall-local:
	rm -f "$(DESTDIR)$(appletdir)/$(APPLET_MAIN_FILE)"

EXTRA_DIST += $(APPLET_MAIN_FILE)
