# vim: set ft=automake :

# for now, assume that icons = SVG
icon_DATA = $(APPLET_ICONS)
icondir = $(datadir)/icons/hicolor/scalable/apps

desktopdir = $(datadir)/avant-window-navigator/applets

desktop_DATA = $(APPLET_NAME).desktop
@INTLTOOL_DESKTOP_RULE@

EXTRA_DIST = \
	$(icon_DATA) \
	$(desktop_DATA).in

CLEANFILES = $(desktop_DATA)
