# vim: set ft=automake ts=8 sts=8 sw=8 :
include $(top_srcdir)/Makefile.common
include $(top_srcdir)/Makefile.desktop-files

AM_CFLAGS = 			\
	-I$(srcdir)		\
	$(AWN_CFLAGS)		\
	$(APPLET_CFLAGS)	\
	$(NULL)

APPLET_LINKER_FLAGS = -module -avoid-version

appletdir = $(libdir)/awn/applets/$(APPLET_NAME)

EXTRA_DIST += \
	$(desktop_DATA:.desktop=.desktop.in.in) \
	$(NULL)
