install: awn.py
	cp awn.py /usr/lib/exaile/python2.4/
	cp awn.py /usr/lib/exaile/python2.5/
	chmod +x /usr/lib/exaile/python2.4/awn.py
	chmod +x /usr/lib/exaile/python2.5/awn.py

uninstall: awn.py
	rm /usr/lib/exaile/python2.4/awn.py
	rm /usr/lib/exaile/python2.5/awn.py
