install: artdisplay-awn
	cp -r artdisplay-awn/ /usr/lib/rhythmbox/plugins/
	cp -r awn-menus/ /usr/lib/rhythmbox/plugins/

uninstall: artdisplay-awn
	rm -r /usr/lib/rhythmbox/plugins/artdisplay-awn/
	rm -r /usr/lib/rhythmbox/plugins/awn-menus/
