#
# Main menu
#
usr/lib/awn/applets/main-menu/*.so
usr/share/avant-window-navigator/applets/main-menu.desktop
#
# Sysmon
#
usr/share/avant-window-navigator/applets/sysmon.desktop
usr/share/avant-window-navigator/schemas/awn-applet-sysmon.schema-ini
usr/lib/awn/applets/sysmon/*.so
etc/gconf/schemas/awn-applet-sysmon.schemas
####################
# Disabled applets #
####################
#
# Filebrowser
#
#usr/lib/awn/applets/filebrowser/*.so
#usr/share/avant-window-navigator/applets/filebrowser.desktop
#usr/share/icons/hicolor/scalable/apps/filebrowser.svg
#etc/gconf/schemas/filebrowser.schemas
#
# Trasher
#
#
# Webapplet
#
#usr/lib/awn/applets/webapplet/*.so
#usr/share/avant-window-navigator/applets/webapplet.desktop
#usr/share/avant-window-navigator/schemas/awn-applet-webapplet.schema-ini
#etc/gconf/schemas/awn-applet-webapplet.schemas
#
#usr/lib/awn/applets/trasher/*.so
#usr/share/avant-window-navigator/applets/trasher.desktop
