#
# Calendar
#
etc/gconf/schemas/awn-applet-digital-clock.schemas
usr/share/avant-window-navigator/applets/calendar/
usr/share/avant-window-navigator/applets/calendar.desktop
usr/share/avant-window-navigator/schemas/awn-applet-digital-clock.schema-ini
#
# Digital Clock
#
etc/gconf/schemas/awn-applet-digital-clock.schemas
usr/share/avant-window-navigator/applets/digital-clock/
usr/share/avant-window-navigator/applets/digital-clock.desktop
usr/share/avant-window-navigator/schemas/awn-applet-digital-clock.schema-ini
usr/share/icons/hicolor/scalable/apps/awn-applet-digital-clock.svg
#
# Media-icons
#
usr/share/avant-window-navigator/applets/media-icons/*.py
usr/share/avant-window-navigator/applets/media-icons/icons/*.svg
usr/share/avant-window-navigator/applets/media-icon-previous.desktop
usr/share/avant-window-navigator/applets/media-icon-next.desktop
usr/share/avant-window-navigator/applets/media-icons.desktop
#
# Mimenu
#
usr/share/avant-window-navigator/applets/mimenu/*.py
usr/share/avant-window-navigator/applets/mimenu/icons/*.svg
usr/share/avant-window-navigator/applets/mimenu.desktop
#
# Pandora
#
usr/share/avant-window-navigator/applets/pandora/
usr/share/avant-window-navigator/applets/pandora.desktop
etc/gconf/schemas/awn-applet-pandora.schemas
usr/share/avant-window-navigator/schemas/awn-applet-pandora.schema-ini
#
# Tomboy
#
usr/share/avant-window-navigator/applets/tomboy-applet/
usr/share/avant-window-navigator/applets/tomboy-applet.desktop
#
# YAMA
#
usr/share/avant-window-navigator/applets/yama/
usr/share/avant-window-navigator/applets/yama.desktop
#
####################
# Disabled applets #
####################
#
#usr/share/avant-window-navigator/applets/comic/
#usr/share/avant-window-navigator/applets/comic.desktop
#
# Awn-meebo
#
#usr/share/avant-window-navigator/applets/awn-meebo/
#usr/share/avant-window-navigator/applets/awn-meebo/icons/
#usr/share/avant-window-navigator/applets/awn-meebo/profile/
#usr/share/avant-window-navigator/applets/awn-meebo.desktop
#
# Digg
#
#usr/share/avant-window-navigator/applets/digg/
#usr/share/avant-window-navigator/applets/digg.desktop
#
# Rtm
#
#usr/share/avant-window-navigator/applets/rtm/
#usr/share/avant-window-navigator/applets/rtm.desktop
