.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AVANT-WINDOW-NAVIGATOR SECTION "juin 25, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
avant-window-navigator \- program to do something
.SH SYNOPSIS
.B The avant-window-navigator is a MacOS X like panel for the GNOME Desktop written in C. Besides launchers that can be dragged onto the bar it features a task bar that behaves similar to the MacOSX dock. The window navigator uses the composite extension for transparency and other effects.
.RI avant-preferences Launch the preference window
.br
.B bar
.RI avant-applets Launch the configuration window for the applets
.br
.B bar
.RI avant-launchers Launch the configuration window for the launchers
.SH DESCRIPTION
This manual page documents briefly the
.B avant-window-navigator
and
.B bar
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBavant-window-navigator\fP is a program that...
.\".SH OPTIONS
.\"These programs follow the usual GNU command line syntax, with long
.\"options starting with two dashes (`-').
.\"A summary of options is included below.
.\"For a complete description, see the Info files.
.\".TP
.\".B \-h, \-\-help
.\"Show summary of options.
.\".TP
.\".B \-v, \-\-version
.\"Show version of program.
.\".SH SEE ALSO
.\".BR bar (1),
.\".BR baz (1).
.\".br
.\"The programs are documented fully by
.\".IR "The Rise and Fall of a Fooish Bar" ,
.\"available via the Info system.
.SH AUTHOR
avant-window-navigator was written by Neil Jagdish Patel <njpatel@gmail.com>.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
